/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2021-02-13 20:33:54.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Category extends Model {
}

module.exports = (sequelize, extend) => {
  Category.init(extend({
    categoryId: {
      type: DataTypes.TINYINT,
      field: 'category_id',
      primaryKey: true,
      autoIncrement: true
    },
    name: {
      type: DataTypes.STRING(25),
      field: 'name',
      allowNull: false
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'Category',
    tableName: 'category',
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Category.associate = () => {
    // 1 <=> N association
    Category.hasMany(sequelize.models.FilmCategory, {
      foreignKey: {
        name: 'categoryId',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      tarketKey: 'categoryId'
    })
  }

  return Category
}
