/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.2.2-dev (node-Sequelize6 dev) on 2023-03-09 10:26:14.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes } = require('sequelize')


module.exports = (sequelize, extend) => {
  const Model = sequelize.define('City', extend({
    cityId: {
      type: DataTypes.SMALLINT,
      field: 'city_id',
      primaryKey: true,
      autoIncrement: true
    },
    city: {
      type: DataTypes.STRING(50),
      field: 'city',
      allowNull: false
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'City',
    tableName: 'city',
    indexes: [
      {
        name: 'idx_fk_country_id',
        fields: ['country_id']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Model.associate = () => {
    // 1 <=> N association
    Model.hasMany(sequelize.models.Address, {
      foreignKey: {
        name: 'cityId',
        field: 'city_id',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'cityId',
      as: 'Addresses'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Country, {
      foreignKey: {
        name: 'countryId',
        field: 'country_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'countryId'
    })
  }

  return Model
}
