/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.2.2-dev (node-Sequelize6 dev) on 2023-03-09 10:38:38.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes } = require('sequelize')


module.exports = (sequelize, extend) => {
  const Model = sequelize.define('Customer', extend({
    customerId: {
      type: DataTypes.SMALLINT,
      field: 'customer_id',
      primaryKey: true,
      autoIncrement: true
    },
    firstName: {
      type: DataTypes.STRING(45),
      field: 'first_name',
      allowNull: false
    },
    lastName: {
      type: DataTypes.STRING(45),
      field: 'last_name',
      allowNull: false
    },
    email: {
      type: DataTypes.STRING(50),
      field: 'email'
    },
    active: {
      type: DataTypes.BOOLEAN,
      field: 'active',
      allowNull: false,
      defaultValue: true
    },
    createDate: {
      type: DataTypes.DATE,
      field: 'create_date',
      allowNull: false
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'Customer',
    tableName: 'customer',
    indexes: [
      {
        name: 'idx_fk_store_id',
        fields: ['store_id']
      },
      {
        name: 'idx_fk_customer_address_id',
        fields: ['address_id']
      },
      {
        name: 'idx_last_name',
        fields: ['last_name']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Model.associate = () => {
    // 1 <=> N association
    Model.hasMany(sequelize.models.Payment, {
      foreignKey: {
        name: 'customerId',
        field: 'customer_id',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'customerId',
      as: 'Payments'
    })

    // 1 <=> N association
    Model.hasMany(sequelize.models.Rental, {
      foreignKey: {
        name: 'customerId',
        field: 'customer_id',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'customerId',
      as: 'Rentals'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Store, {
      foreignKey: {
        name: 'storeId',
        field: 'store_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'storeId'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Address, {
      foreignKey: {
        name: 'addressId',
        field: 'address_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'addressId'
    })
  }

  return Model
}
