/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2021-04-02 10:49:25.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Customer extends Model {
}

module.exports = (sequelize, extend) => {
  Customer.init(extend({
    customerId: {
      type: DataTypes.SMALLINT,
      field: 'customer_id',
      primaryKey: true,
      autoIncrement: true
    },
    firstName: {
      type: DataTypes.STRING(45),
      field: 'first_name',
      allowNull: false
    },
    lastName: {
      type: DataTypes.STRING(45),
      field: 'last_name',
      allowNull: false
    },
    email: {
      type: DataTypes.STRING(50),
      field: 'email'
    },
    active: {
      type: DataTypes.BOOLEAN,
      field: 'active',
      allowNull: false,
      defaultValue: true
    },
    createDate: {
      type: DataTypes.DATE,
      field: 'create_date',
      allowNull: false
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'Customer',
    tableName: 'customer',
    indexes: [
      {
        name: 'idx_fk_store_id',
        fields: ['store_id']
      },
      {
        name: 'idx_fk_customer_address_id',
        fields: ['address_id']
      },
      {
        name: 'idx_last_name',
        fields: ['last_name']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Customer.associate = () => {
    // 1 <=> N association
    Customer.hasMany(sequelize.models.Payment, {
      foreignKey: {
        name: 'customerId',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'customerId',
      as: 'Payments'
    })

    // 1 <=> N association
    Customer.hasMany(sequelize.models.Rental, {
      foreignKey: {
        name: 'customerId',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'customerId',
      as: 'Rentals'
    })

    // N <=> 1 association
    Customer.belongsTo(sequelize.models.Store, {
      foreignKey: {
        name: 'storeId',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'storeId'
    })

    // N <=> 1 association
    Customer.belongsTo(sequelize.models.Address, {
      foreignKey: {
        name: 'addressId',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'addressId'
    })
  }

  return Customer
}
