/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.2.2-dev (node-Sequelize6 dev) on 2023-03-09 10:26:14.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes } = require('sequelize')


module.exports = (sequelize, extend) => {
  const Model = sequelize.define('FilmText', extend({
    filmId: {
      type: DataTypes.SMALLINT,
      field: 'film_id',
      primaryKey: true,
      allowNull: false
    },
    title: {
      type: DataTypes.STRING(255),
      field: 'title',
      allowNull: false
    },
    description: {
      type: DataTypes.TEXT,
      field: 'description'
    }
  }), {
    sequelize: sequelize,
    modelName: 'FilmText',
    tableName: 'film_text',
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Model.associate = () => {
  }

  return Model
}
