/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.2.2-dev (node-Sequelize6 dev) on 2023-03-09 10:26:14.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes } = require('sequelize')


module.exports = (sequelize, extend) => {
  const Model = sequelize.define('Film', extend({
    filmId: {
      type: DataTypes.SMALLINT,
      field: 'film_id',
      primaryKey: true,
      autoIncrement: true
    },
    title: {
      type: DataTypes.STRING(128),
      field: 'title',
      allowNull: false
    },
    description: {
      type: DataTypes.TEXT,
      field: 'description'
    },
    releaseYear: {
      type: DataTypes.INTEGER,
      field: 'release_year'
    },
    rentalDuration: {
      type: DataTypes.SMALLINT,
      field: 'rental_duration',
      allowNull: false,
      defaultValue: '3'
    },
    rentalRate: {
      type: DataTypes.DECIMAL(4, 2),
      field: 'rental_rate',
      allowNull: false,
      defaultValue: '4.99'
    },
    length: {
      type: DataTypes.SMALLINT,
      field: 'length'
    },
    replacementCost: {
      type: DataTypes.DECIMAL(5, 2),
      field: 'replacement_cost',
      allowNull: false,
      defaultValue: '19.99'
    },
    rating: {
      type: DataTypes.ENUM('G', 'PG', 'PG-13', 'R', 'NC-17'),
      field: 'rating',
      defaultValue: 'G'
    },
    specialFeatures: {
      type: DataTypes.STRING,
      field: 'special_features'
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'Film',
    tableName: 'film',
    indexes: [
      {
        name: 'idx_title',
        fields: ['title']
      },
      {
        name: 'idx_fk_language_id',
        fields: ['language_id']
      },
      {
        name: 'idx_fk_original_language_id',
        fields: ['original_language_id']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Model.associate = () => {
    // 1 <=> N association
    Model.hasMany(sequelize.models.Inventory, {
      foreignKey: {
        name: 'filmId',
        field: 'film_id',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'filmId',
      as: 'Inventories'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Language, {
      foreignKey: {
        name: 'languageId',
        field: 'language_id',
        allowNull: false
      },
      targetKey: 'languageId',
      constraints: false
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Language, {
      foreignKey: {
        name: 'originalLanguageId',
        field: 'original_language_id',
        allowNull: true
      },
      targetKey: 'languageId',
      as: 'OriginalLanguage',
      constraints: false
    })

    // N <=> M association
    Model.belongsToMany(sequelize.models.Actor, {
      through: 'film_actor',
      foreignKey: {
        name: 'film_id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'actorId',
      as: 'Actors'
    })

    // N <=> M association
    Model.belongsToMany(sequelize.models.Category, {
      through: 'film_category',
      foreignKey: {
        name: 'film_id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'categoryId',
      as: 'Categories'
    })
  }

  return Model
}
