/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2021-02-13 20:33:54.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class FilmActor extends Model {
}

module.exports = (sequelize, extend) => {
  FilmActor.init(extend({
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'FilmActor',
    tableName: 'film_actor',
    indexes: [
      {
        name: 'idx_fk_film_id',
        fields: ['film_id']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  FilmActor.associate = () => {
    // N <=> 1 association
    FilmActor.belongsTo(sequelize.models.Actor, {
      foreignKey: {
        name: 'actorId',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      tarketKey: 'actorId'
    })

    // N <=> 1 association
    FilmActor.belongsTo(sequelize.models.Film, {
      foreignKey: {
        name: 'filmId',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      tarketKey: 'filmId'
    })
  }

  return FilmActor
}
