/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2021-02-13 20:33:54.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class FilmCategory extends Model {
}

module.exports = (sequelize, extend) => {
  FilmCategory.init(extend({
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'FilmCategory',
    tableName: 'film_category',
    indexes: [
      {
        name: 'fk_film_category_category',
        fields: ['category_id']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  FilmCategory.associate = () => {
    // N <=> 1 association
    FilmCategory.belongsTo(sequelize.models.Film, {
      foreignKey: {
        name: 'filmId',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      tarketKey: 'filmId'
    })

    // N <=> 1 association
    FilmCategory.belongsTo(sequelize.models.Category, {
      foreignKey: {
        name: 'categoryId',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      tarketKey: 'categoryId'
    })
  }

  return FilmCategory
}
