/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.2.2-dev (node-Sequelize6 dev) on 2023-03-09 10:38:38.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes } = require('sequelize')


module.exports = (sequelize, extend) => {
  const Model = sequelize.define('Inventory', extend({
    inventoryId: {
      type: DataTypes.INTEGER,
      field: 'inventory_id',
      primaryKey: true,
      autoIncrement: true
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'Inventory',
    tableName: 'inventory',
    indexes: [
      {
        name: 'idx_fk_inventory_film_id',
        fields: ['film_id']
      },
      {
        name: 'idx_store_id_film_id',
        fields: ['store_id', 'film_id']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Model.associate = () => {
    // 1 <=> N association
    Model.hasMany(sequelize.models.Rental, {
      foreignKey: {
        name: 'inventoryId',
        field: 'inventory_id',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'inventoryId',
      as: 'Rentals'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Film, {
      foreignKey: {
        name: 'filmId',
        field: 'film_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'filmId'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Store, {
      foreignKey: {
        name: 'storeId',
        field: 'store_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'storeId'
    })
  }

  return Model
}
