/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2021-02-13 20:33:54.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Language extends Model {
}

module.exports = (sequelize, extend) => {
  Language.init(extend({
    languageId: {
      type: DataTypes.TINYINT,
      field: 'language_id',
      primaryKey: true,
      autoIncrement: true
    },
    name: {
      type: DataTypes.STRING(20),
      field: 'name',
      allowNull: false
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'Language',
    tableName: 'language',
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Language.associate = () => {
    // 1 <=> N association
    Language.hasMany(sequelize.models.Film, {
      foreignKey: {
        name: 'languageId',
        allowNull: false
      },
      tarketKey: 'languageId',
      constraints: false
    })

    // 1 <=> N association
    Language.hasMany(sequelize.models.Film, {
      foreignKey: {
        name: 'originalLanguageId',
        allowNull: true
      },
      tarketKey: 'languageId',
      as: 'AsOriginalFilm',
      constraints: false
    })
  }

  return Language
}
