/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.2.2-dev (node-Sequelize6 dev) on 2023-03-09 10:38:38.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes } = require('sequelize')


module.exports = (sequelize, extend) => {
  const Model = sequelize.define('Rental', extend({
    rentalId: {
      type: DataTypes.INTEGER,
      field: 'rental_id',
      primaryKey: true,
      autoIncrement: true
    },
    rentalDate: {
      type: DataTypes.DATE,
      field: 'rental_date',
      allowNull: false
    },
    returnDate: {
      type: DataTypes.DATE,
      field: 'return_date'
    },
    lastUpdate: {
      type: DataTypes.DATE,
      field: 'last_update',
      allowNull: false,
      defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
    }
  }), {
    sequelize: sequelize,
    modelName: 'Rental',
    tableName: 'rental',
    indexes: [
      {
        name: 'rental_date',
        fields: ['rental_date', 'inventory_id', 'customer_id'],
        unique: true
      },
      {
        name: 'idx_fk_inventory_id',
        fields: ['inventory_id']
      },
      {
        name: 'idx_fk_customer_id',
        fields: ['customer_id']
      },
      {
        name: 'idx_fk_staff_id',
        fields: ['staff_id']
      }
    ],
    timestamps: false,
    underscored: true,
    syncOnAssociation: false
  })

  Model.associate = () => {
    // 1 <=> N association
    Model.hasMany(sequelize.models.Payment, {
      foreignKey: {
        name: 'rentalId',
        field: 'rental_id',
        allowNull: true
      },
      onUpdate: 'CASCADE',
      onDelete: 'SET NULL',
      targetKey: 'rentalId',
      as: 'Payments'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Inventory, {
      foreignKey: {
        name: 'inventoryId',
        field: 'inventory_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'inventoryId'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Customer, {
      foreignKey: {
        name: 'customerId',
        field: 'customer_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'customerId'
    })

    // N <=> 1 association
    Model.belongsTo(sequelize.models.Staff, {
      foreignKey: {
        name: 'staffId',
        field: 'staff_id',
        allowNull: false
      },
      onUpdate: 'RESTRICT',
      targetKey: 'staffId'
    })
  }

  return Model
}
